### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by prysme01** [onigoetz/Comics-Reader#110]
Hello, trying to test your application but

docker run -v /your-images-dir:/root/comic/ -p 10000:8080 --rm onigoetz/comicsreader
yarn run v1.17.3
$ NODE_ENV=production node server/index.js
Generating index
Starting server
Started server on http://localhost:8080/
Found 0 books or directories in 0.264 s
Found 0 thumbnails already
Computed thumbnails in 0 s
Could not create index TypeError: Cannot read property 'toFixed' of undefined
    at addRow (/usr/src/app/server/tree/IndexCreator.js:175:37)
    at IndexCreator.writeStats (/usr/src/app/server/tree/IndexCreator.js:185:5)
    at IndexCreator.getRootNode (/usr/src/app/server/tree/IndexCreator.js:214:10)
GET /api/auth_mode 200 16 - 11.781 ms
GET /api/indexready 200 50 - 1.283 ms
Creating migration table
Applying migrations, your DB is at version 0 going to 2
Applying migrations to version 1
Creating 'read' table
Applying migrations to version 2
Creating 'users' table
Your DB is up to date
GET /api/list 404 14 - 537.040 ms
Error: Failed with status 404 and message: Not Found
    at onlySuccess (/usr/src/app/.next/server/static/G9Fc4B5gf2ZpvxMvsOAP-/pages/index.js:1013:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Function.module.exports.czAh.ListManager.getInitialProps (/usr/src/app/.next/server/static/G9Fc4B5gf2ZpvxMvsOAP-/pages/index.js:1613:7)
    at async Function.component.getInitialProps (/usr/src/app/.next/server/static/G9Fc4B5gf2ZpvxMvsOAP-/pages/index.js:1100:65)
    at async Function.component.getInitialProps (/usr/src/app/.next/server/static/G9Fc4B5gf2ZpvxMvsOAP-/pages/index.js:356:65)
    at async loadGetInitialProps (/usr/src/app/.next/server/static/G9Fc4B5gf2ZpvxMvsOAP-/pages/_document.js:1028:17)
GET / 500 - - 722.150 ms
GET /_next/static/G9Fc4B5gf2ZpvxMvsOAP-/pages/_app.js 200 - - 7.903 ms
GET /_next/static/chunks/commons.15009571affea72f6845.js 200 - - 6.130 ms
GET /_next/static/runtime/main-3a4d315d95379e5868a8.js 200 - - 3.830 ms
GET /_next/static/runtime/webpack-4b444dab214c6491079c.js 200 - - 3.709 ms
GET /_next/static/css/commons.b1d4bd72.chunk.css 200 - - 3.849 ms
GET /_next/static/G9Fc4B5gf2ZpvxMvsOAP-/pages/_error.js 200 - - 1.303 ms
GET /api/list 404 14 - 0.715 ms

**Comment by onigoetz** [comment]
Hello, 
According to the log, there are no books that were found.

This is probably why you get a 404.
Did you change the `/your-images-dir` to a Directory containing your comic books ?

**Comment by onigoetz** [comment]
Closing because of no activity
