### ISSUE TITLE
Failing to run.

### ISSUE THREAD

**Issue by RattyDAVE** [onigoetz/Comics-Reader#2]
Here is the output.

Thank you.

```
# docker run -v /share/ebooks:/comics -p 8080:8080 --rm onigoetz/comicsreader
Unable to find image 'onigoetz/comicsreader:latest' locally
latest: Pulling from onigoetz/comicsreader
54f7e8ac135a: Pull complete 
d6341e30912f: Pull complete 
087a57faf949: Pull complete 
5d71636fb824: Pull complete 
0c1db9598990: Pull complete 
89669bc2deb2: Pull complete 
680b586c807d: Pull complete 
16f1b885efe0: Pull complete 
3a4fa74685f5: Pull complete 
278d8a99f6c7: Pull complete 
731ab23fc19a: Pull complete 
2eb1d60288ec: Pull complete 
23714a9e6e6d: Pull complete 
390cd13be2ed: Pull complete 
9bd43f543fbd: Pull complete 
1b733308760e: Pull complete 
9c003f24828b: Pull complete 
Digest: sha256:2b57bf4550bc3ad26cb83912ee97fc35767ae578644ec13298582b7d497b81ac
Status: Downloaded newer image for onigoetz/comicsreader:latest
yarn run v1.12.3
$ node src/server/index.js

/usr/src/app/node_modules/better-sqlite3/lib/database.js:43
        return new CPPDatabase(filename, filenameGiven, memory || anonymous, readonly, fileMustExist, timeout);
               ^
SqliteError: unable to open database file
    at Database (/usr/src/app/node_modules/better-sqlite3/lib/database.js:43:9)
    at Object.<anonymous> (/usr/src/app/src/server/db.js:9:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/src/app/src/server/index.js:25:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by RattyDAVE** [comment]
Ah.. No it is not I was unaware it writes anything.

**Comment by onigoetz** [comment]
I'll add something to the readme.

yes it writes things for two reasons : 
1. The database to keep track of read comics
2. The cache (a `cache` directory) directly at the root, that will contain thumbnails, and extracted pages. Those are generated on the fly on first access, but are kept after so that it's quicker to access after. Also, the comics reader never sends the original image on the device, as they are generally way too big for what the device is able to display. Saving both bandwidth and processing power.
